# 镜像需要的基础镜像，常用的还有openjdk:8 ，openjdk:8-alpine
FROM java:8

# 将当前目录下的jar复制到docker容器的根目录 / 下
ADD HelloJenkins-1.0-SNAPSHOT.jar /HelloJenkins-1.0-SNAPSHOT.jar

# 声明服务运行的端口
EXPOSE 8081

# 指定docker容器启动时运行的jar包
ENTRYPOINT ["java", "-jar", "/HelloJenkins-1.0-SNAPSHOT.jar"]

# 指定维护者
MAINTAINER Biao